CC=gcc

all:
	$(CC) -g -w -o game.exe \
		-I. \
		-L. \
		-D_GNU_SOURCE=1 -Dmain=SDL_main -DWIN32 \
		-lmingw32 -mwindows \
		SDL.dll \
		SDL_image.dll \
		SDL_gfx.dll \
		libSDLmain.a \
		enet.dll \
		ferite.dll \
		Engine/game.c \
		Engine/array.c \
		Engine/string.c \
		Engine/number.c \
		Engine/engine.c \
		Engine/key.c \
		Engine/image.c \
		Engine/network_enet.c
	$(CC) -g -w -o server.exe \
		-I. \
		-L. \
		-D_GNU_SOURCE=1 -Dmain=SDL_main -DWIN32 \
		-lmingw32 -mwindows \
		SDL.dll \
		SDL_image.dll \
		SDL_gfx.dll \
		libSDLmain.a \
		enet.dll \
		ferite.dll \
		Engine/server.c \
		Engine/array.c \
		Engine/string.c \
		Engine/number.c \
		Engine/engine.c \
		Engine/key.c \
		Engine/image.c \
		Engine/network_enet.c